In [2]:
!mamba install pandas numpy matplotlib

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 7.398 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.2.1   pyh145f28c_0         conda-forge

In [3]:
import pandas as pd
import numpy as np

In [7]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles and folders available:")
print(os.listdir())

Current folder:
/drive/notebooks/project

Files and folders available:
['EducationLevel.csv', 'Employee.csv', 'HR_Attrition_Analytics.ipynb', 'PerformanceRating.csv', 'RatingLevel.csv', 'SatisfiedLevel.csv']

### Load the five datasets

In [9]:
employee = pd.read_csv("Employee.csv")
performance = pd.read_csv("PerformanceRating.csv")
education = pd.read_csv("EducationLevel.csv")
rating = pd.read_csv("RatingLevel.csv")
satisfaction = pd.read_csv("SatisfiedLevel.csv")

### Check the dataset dimensions

In [10]:
print("Employee:", employee.shape)
print("Performance:", performance.shape)
print("Education:", education.shape)
print("Rating:", rating.shape)
print("Satisfaction:", satisfaction.shape)

Employee: (1470, 23)
Performance: (6709, 11)
Education: (5, 2)
Rating: (5, 2)
Satisfaction: (5, 2)

### Display the columns

In [11]:
print("Employee Columns:")
print(employee.columns.tolist())

print("\nPerformance Columns:")
print(performance.columns.tolist())

print("\nEducation Columns:")
print(education.columns.tolist())

print("\nRating Columns:")
print(rating.columns.tolist())

print("\nSatisfaction Columns:")
print(satisfaction.columns.tolist())

Employee Columns:
['EmployeeID', 'FirstName', 'LastName', 'Gender', 'Age', 'BusinessTravel', 'Department', 'DistanceFromHome (KM)', 'State', 'Ethnicity', 'Education', 'EducationField', 'JobRole', 'MaritalStatus', 'Salary', 'StockOptionLevel', 'OverTime', 'HireDate', 'Attrition', 'YearsAtCompany', 'YearsInMostRecentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

Performance Columns:
['PerformanceID', 'EmployeeID', 'ReviewDate', 'EnvironmentSatisfaction', 'JobSatisfaction', 'RelationshipSatisfaction', 'TrainingOpportunitiesWithinYear', 'TrainingOpportunitiesTaken', 'WorkLifeBalance', 'SelfRating', 'ManagerRating']

Education Columns:
['EducationLevelID', 'EducationLevel']

Rating Columns:
['RatingID', 'RatingLevel']

Satisfaction Columns:
['SatisfactionID', 'SatisfactionLevel']

In [12]:
print("EMPLOYEE DATA")
display(employee.head())

print("\nPERFORMANCE DATA")
display(performance.head())

print("\nEDUCATION DATA")
display(education.head())

print("\nRATING DATA")
display(rating.head())

print("\nSATISFACTION DATA")
display(satisfaction.head())

EMPLOYEE DATA

,EmployeeID,FirstName,LastName,Gender,Age,BusinessTravel,Department,DistanceFromHome (KM),State,Ethnicity,...,MaritalStatus,Salary,StockOptionLevel,OverTime,HireDate,Attrition,YearsAtCompany,YearsInMostRecentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,Divorced,102059,1,No,2012-01-03,No,10,4,9,7
1,CBCB-9C9D,Leonerd,Aland,Male,38,Some Travel,Sales,23,CA,White,...,Single,157718,0,Yes,2012-01-04,No,10,6,10,0
2,95D7-1CE9,Ahmed,Sykes,Male,43,Some Travel,Human Resources,29,CA,Asian or Asian American,...,Married,309964,1,No,2012-01-04,No,10,6,10,8
3,47A0-559B,Ermentrude,Berrie,Non-Binary,39,Some Travel,Technology,12,IL,White,...,Married,293132,0,No,2012-01-05,No,10,10,10,0
4,42CC-040A,Stace,Savege,Female,29,Some Travel,Human Resources,29,CA,White,...,Single,49606,0,No,2012-01-05,Yes,6,1,1,6

PERFORMANCE DATA

,PerformanceID,EmployeeID,ReviewDate,EnvironmentSatisfaction,JobSatisfaction,RelationshipSatisfaction,TrainingOpportunitiesWithinYear,TrainingOpportunitiesTaken,WorkLifeBalance,SelfRating,ManagerRating
0,PR01,79F7-78EC,1/2/2013,5,4,5,1,0,4,4,4
1,PR02,B61E-0F26,1/3/2013,5,4,4,1,3,4,4,3
2,PR03,F5E3-48BB,1/3/2013,3,4,5,3,2,3,5,4
3,PR04,0678-748A,1/4/2013,5,3,2,2,0,2,3,2
4,PR05,541F-3E19,1/4/2013,5,2,3,1,0,4,4,3

EDUCATION DATA

   EducationLevelID            EducationLevel
0                 1  No Formal Qualifications
1                 2              High School
2                 3                Bachelors
3                 4                  Masters
4                 5                 Doctorate

RATING DATA

   RatingID           RatingLevel
0         1          Unacceptable
1         2     Needs Improvement
2         3     Meets Expectation
3         4  Exceeds Expectation
4         5      Above and Beyond

SATISFACTION DATA

   SatisfactionID  SatisfactionLevel
0               1  Very Dissatisfied
1               2       Dissatisfied
2               3            Neutral
3               4         Satisfied
4               5     Very Satisfied

### Check data types

In [13]:
print("EMPLOYEE DATA TYPES")
employee.info()

print("\nPERFORMANCE DATA TYPES")
performance.info()

EMPLOYEE DATA TYPES
<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmployeeID               1470 non-null   str
 1   FirstName                1470 non-null   str
 2   LastName                 1470 non-null   str
 3   Gender                   1470 non-null   str
 4   Age                      1470 non-null   int64
 5   BusinessTravel           1470 non-null   str
 6   Department               1470 non-null   str
 7   DistanceFromHome (KM)    1470 non-null   int64
 8   State                    1470 non-null   str
 9   Ethnicity                1470 non-null   str
 10  Education                1470 non-null   int64
 11  EducationField           1470 non-null   str
 12  JobRole                  1470 non-null   str
 13  MaritalStatus            1470 non-null   str
 14  Salary                   1470 non-null   int64
 15  StockOptionLevel         1470 non-null   int64
 16  OverTime                 1470 non-null   str
 17  HireDate                 1470 non-null   str
 18  Attrition                1470 non-null   str
 19  YearsAtCompany           1470 non-null   int64
 20  YearsInMostRecentRole    1470 non-null   int64
 21  YearsSinceLastPromotion  1470 non-null   int64
 22  YearsWithCurrManager     1470 non-null   int64
dtypes: int64(9), str(14)
memory usage: 183.8 KB

PERFORMANCE DATA TYPES
<class 'pandas.DataFrame'>
RangeIndex: 6709 entries, 0 to 6708
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   PerformanceID                    6709 non-null   str
 1   EmployeeID                       6709 non-null   str
 2   ReviewDate                       6709 non-null   str
 3   EnvironmentSatisfaction          6709 non-null   int64
 4   JobSatisfaction                  6709 non-null   int64
 5   RelationshipSatisfaction         6709 non-null   int64
 6   TrainingOpportunitiesWithinYear  6709 non-null   int64
 7   TrainingOpportunitiesTaken       6709 non-null   int64
 8   WorkLifeBalance                  6709 non-null   int64
 9   SelfRating                       6709 non-null   int64
 10  ManagerRating                    6709 non-null   int64
dtypes: int64(8), str(3)
memory usage: 498.0 KB

### Check missing values

In [14]:
print("Employee Missing Values:")
print(employee.isnull().sum())

print("\nPerformance Missing Values:")
print(performance.isnull().sum())

print("\nEducation Missing Values:")
print(education.isnull().sum())

print("\nRating Missing Values:")
print(rating.isnull().sum())

print("\nSatisfaction Missing Values:")
print(satisfaction.isnull().sum())

Employee Missing Values:
EmployeeID                 0
FirstName                  0
LastName                   0
Gender                     0
Age                        0
BusinessTravel             0
Department                 0
DistanceFromHome (KM)      0
State                      0
Ethnicity                  0
Education                  0
EducationField             0
JobRole                    0
MaritalStatus              0
Salary                     0
StockOptionLevel           0
OverTime                   0
HireDate                   0
Attrition                  0
YearsAtCompany             0
YearsInMostRecentRole      0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

Performance Missing Values:
PerformanceID                      0
EmployeeID                         0
ReviewDate                         0
EnvironmentSatisfaction            0
JobSatisfaction                    0
RelationshipSatisfaction           0
TrainingOpportunitiesWithinYear    0
TrainingOpportunitiesTaken         0
WorkLifeBalance                    0
SelfRating                         0
ManagerRating                      0
dtype: int64

Education Missing Values:
EducationLevelID    0
EducationLevel      0
dtype: int64

Rating Missing Values:
RatingID       0
RatingLevel    0
dtype: int64

Satisfaction Missing Values:
SatisfactionID       0
SatisfactionLevel    0
dtype: int64

### Check duplicates

In [15]:
print("Employee duplicate rows:", employee.duplicated().sum())
print("Performance duplicate rows:", performance.duplicated().sum())

Employee duplicate rows: 0
Performance duplicate rows: 0

In [16]:
print("Total Employee IDs:", employee["EmployeeID"].count())
print("Unique Employee IDs:", employee["EmployeeID"].nunique())

Total Employee IDs: 1470
Unique Employee IDs: 1470

In [17]:
print("Performance rows:", len(performance))
print("Unique Employee IDs:", performance["EmployeeID"].nunique())

Performance rows: 6709
Unique Employee IDs: 1280

### Check important categorical columns

In [18]:
print("ATTRITION")
print(employee["Attrition"].value_counts())

print("\nDEPARTMENT")
print(employee["Department"].value_counts())

print("\nJOB ROLE")
print(employee["JobRole"].value_counts())

print("\nGENDER")
print(employee["Gender"].value_counts())

print("\nOVERTIME")
print(employee["OverTime"].value_counts())

print("\nBUSINESS TRAVEL")
print(employee["BusinessTravel"].value_counts())

ATTRITION
Attrition
No     1233
Yes     237
Name: count, dtype: int64

DEPARTMENT
Department
Technology         961
Sales              446
Human Resources     63
Name: count, dtype: int64

JOB ROLE
JobRole
Sales Executive              327
Software Engineer            294
Data Scientist               261
Machine Learning Engineer    146
Senior Software Engineer     132
Sales Representative          83
Engineering Manager           75
Analytics Manager             52
Manager                       37
HR Executive                  28
Recruiter                     24
HR Business Partner            7
HR Manager                     4
Name: count, dtype: int64

GENDER
Gender
Female               675
Male                 651
Non-Binary           124
Prefer Not To Say     20
Name: count, dtype: int64

OVERTIME
OverTime
No     1054
Yes     416
Name: count, dtype: int64

BUSINESS TRAVEL
BusinessTravel
Some Travel           1043
Frequent Traveller     277
No Travel              150
Name: count, dtype: int64

### Check numerical columns

In [21]:
employee.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,1470.0,28.989796,7.993055,18.0,23.0,26.0,34.00,51.0
DistanceFromHome (KM),1470.0,22.502721,12.811124,1.0,12.0,22.0,33.00,45.0
Education,1470.0,2.912925,1.024165,1.0,2.0,3.0,4.00,5.0
Salary,1470.0,112956.497959,103342.889222,20387.0,43580.5,71199.5,142055.75,547204.0
StockOptionLevel,1470.0,0.793878,0.852077,0.0,0.0,1.0,1.00,3.0
YearsAtCompany,1470.0,4.562585,3.288048,0.0,2.0,4.0,7.00,10.0
YearsInMostRecentRole,1470.0,2.293197,2.539093,0.0,0.0,1.0,4.00,10.0
YearsSinceLastPromotion,1470.0,3.440816,2.945194,0.0,1.0,3.0,6.00,10.0
YearsWithCurrManager,1470.0,2.239456,2.505774,0.0,0.0,1.0,4.00,10.0

### Check date columns

In [22]:
print(employee["HireDate"].head())
print(performance["ReviewDate"].head())

0    2012-01-03
1    2012-01-04
2    2012-01-04
3    2012-01-05
4    2012-01-05
Name: HireDate, dtype: str
0    1/2/2013
1    1/3/2013
2    1/3/2013
3    1/4/2013
4    1/4/2013
Name: ReviewDate, dtype: str

In [23]:
employee["HireDate"] = pd.to_datetime(employee["HireDate"])
performance["ReviewDate"] = pd.to_datetime(performance["ReviewDate"])

In [24]:
print(employee["HireDate"].dtype)
print(performance["ReviewDate"].dtype)

datetime64[us]
datetime64[us]

### Check for leading/trailing spaces
Check categorical columns for unwanted leading or trailing spaces.

Although the datasets do not contain missing values or duplicate rows, inconsistent spaces in categorical fields can create incorrect categories during grouping and analysis.

Text fields are therefore cleaned using string trimming.

In [26]:
employee_clean = employee.copy()
performance_clean = performance.copy()
education_clean = education.copy()
rating_clean = rating.copy()
satisfaction_clean = satisfaction.copy()

In [29]:
# Clean text columns in Employee table
categorical_employee = employee_clean.select_dtypes(include='str').columns

for col in categorical_employee:
    employee_clean[col] = employee_clean[col].str.strip()


# Clean text columns in Performance table
categorical_performance = performance_clean.select_dtypes(include='str').columns

for col in categorical_performance:
    performance_clean[col] = performance_clean[col].str.strip()

In [30]:
education_clean["EducationLevel"] = education_clean["EducationLevel"].astype(str).str.strip()
rating_clean["RatingLevel"] = rating_clean["RatingLevel"].astype(str).str.strip()
satisfaction_clean["SatisfactionLevel"] = satisfaction_clean["SatisfactionLevel"].astype(str).str.strip()

In [31]:
print("Employee text columns:")
print(employee_clean.select_dtypes(include='str').columns.tolist())

print("\nPerformance text columns:")
print(performance_clean.select_dtypes(include='str').columns.tolist())

Employee text columns:
['EmployeeID', 'FirstName', 'LastName', 'Gender', 'BusinessTravel', 'Department', 'State', 'Ethnicity', 'EducationField', 'JobRole', 'MaritalStatus', 'OverTime', 'Attrition']

Performance text columns:
['PerformanceID', 'EmployeeID']

### Validate relationships between tables

In [32]:
print("Employee IDs in Employee table:",
      employee_clean["EmployeeID"].nunique())

print("Employee IDs in Performance table:",
      performance_clean["EmployeeID"].nunique())

Employee IDs in Employee table: 1470
Employee IDs in Performance table: 1280

In [33]:
invalid_performance_ids = performance_clean[
    ~performance_clean["EmployeeID"].isin(employee_clean["EmployeeID"])
]

print("Performance records with invalid EmployeeID:",
      len(invalid_performance_ids))

Performance records with invalid EmployeeID: 0

### Create Useful Analytical Columns
Age Group

In [34]:
employee_clean["AgeGroup"] = pd.cut(
    employee_clean["Age"],
    bins=[17, 24, 34, 44, 54],
    labels=["18-24", "25-34", "35-44", "45-54"]
)

print(employee_clean["AgeGroup"].value_counts().sort_index())

AgeGroup
18-24    521
25-34    596
35-44    263
45-54     90
Name: count, dtype: int64

### Salary Band

In [35]:
employee_clean["SalaryBand"] = pd.qcut(
    employee_clean["Salary"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

print(employee_clean["SalaryBand"].value_counts())

SalaryBand
Low          368
Very High    368
Medium       367
High         367
Name: count, dtype: int64

### Tenure Group

In [36]:
employee_clean["TenureGroup"] = pd.cut(
    employee_clean["YearsAtCompany"],
    bins=[-1, 2, 5, 10],
    labels=["0-2 Years", "3-5 Years", "6-10 Years"]
)

print(employee_clean["TenureGroup"].value_counts().sort_index())

TenureGroup
0-2 Years     491
3-5 Years     392
6-10 Years    587
Name: count, dtype: int64

### Promotion Gap Group

In [37]:
employee_clean["PromotionGapGroup"] = pd.cut(
    employee_clean["YearsSinceLastPromotion"],
    bins=[-1, 2, 5, 10],
    labels=["0-2 Years", "3-5 Years", "6-10 Years"]
)

print(employee_clean["PromotionGapGroup"].value_counts().sort_index())

PromotionGapGroup
0-2 Years     662
3-5 Years     429
6-10 Years    379
Name: count, dtype: int64

### Distance Group

In [38]:
employee_clean["DistanceGroup"] = pd.cut(
    employee_clean["DistanceFromHome (KM)"],
    bins=[0, 10, 20, 30, 45],
    labels=["0-10 KM", "11-20 KM", "21-30 KM", "31-45 KM"]
)

print(employee_clean["DistanceGroup"].value_counts().sort_index())

DistanceGroup
0-10 KM     333
11-20 KM    345
21-30 KM    339
31-45 KM    453
Name: count, dtype: int64

### Attrition Flag

In [39]:
employee_clean["AttritionFlag"] = (
    employee_clean["Attrition"] == "Yes"
).astype(int)

print(employee_clean["AttritionFlag"].value_counts())

AttritionFlag
0    1233
1     237
Name: count, dtype: int64

In [40]:
employee_clean[
    [
        "EmployeeID",
        "Age",
        "AgeGroup",
        "Salary",
        "SalaryBand",
        "YearsAtCompany",
        "TenureGroup",
        "YearsSinceLastPromotion",
        "PromotionGapGroup",
        "DistanceFromHome (KM)",
        "DistanceGroup",
        "Attrition",
        "AttritionFlag"
    ]
].head(10)

,EmployeeID,Age,AgeGroup,Salary,SalaryBand,YearsAtCompany,TenureGroup,YearsSinceLastPromotion,PromotionGapGroup,DistanceFromHome (KM),DistanceGroup,Attrition,AttritionFlag
0,3012-1A41,30,25-34,102059,High,10,6-10 Years,9,6-10 Years,27,21-30 KM,No,0
1,CBCB-9C9D,38,35-44,157718,Very High,10,6-10 Years,10,6-10 Years,23,21-30 KM,No,0
2,95D7-1CE9,43,35-44,309964,Very High,10,6-10 Years,10,6-10 Years,29,21-30 KM,No,0
3,47A0-559B,39,35-44,293132,Very High,10,6-10 Years,10,6-10 Years,12,11-20 KM,No,0
4,42CC-040A,29,25-34,49606,Medium,6,6-10 Years,1,0-2 Years,29,21-30 KM,Yes,1
5,C219-6C2E,34,25-34,133468,High,10,6-10 Years,7,6-10 Years,30,21-30 KM,No,0
6,D906-B674,42,35-44,259284,Very High,10,6-10 Years,6,6-10 Years,45,31-45 KM,No,0
7,3C7D-86ED,40,35-44,104426,High,10,6-10 Years,4,3-5 Years,3,0-10 KM,No,0
8,3D71-8DC2,38,35-44,147098,Very High,10,6-10 Years,8,6-10 Years,20,11-20 KM,No,0
9,5476-CA0D,31,25-34,69747,Medium,6,6-10 Years,5,3-5 Years,4,0-10 KM,Yes,1

### First, check the performance rating ranges

In [41]:
performance_columns = [
    "EnvironmentSatisfaction",
    "JobSatisfaction",
    "RelationshipSatisfaction",
    "TrainingOpportunitiesWithinYear",
    "TrainingOpportunitiesTaken",
    "WorkLifeBalance",
    "SelfRating",
    "ManagerRating"
]

for col in performance_columns:
    print(f"\n{col}")
    print(sorted(performance_clean[col].unique()))

EnvironmentSatisfaction
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

JobSatisfaction
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

RelationshipSatisfaction
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

TrainingOpportunitiesWithinYear
[np.int64(1), np.int64(2), np.int64(3)]

TrainingOpportunitiesTaken
[np.int64(0), np.int64(1), np.int64(2), np.int64(3)]

WorkLifeBalance
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

SelfRating
[np.int64(3), np.int64(4), np.int64(5)]

ManagerRating
[np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

### Check PerformanceID uniqueness

In [42]:
print("Total Performance IDs:", performance_clean["PerformanceID"].count())
print("Unique Performance IDs:", performance_clean["PerformanceID"].nunique())

Total Performance IDs: 6709
Unique Performance IDs: 6709

### Check EmployeeID relationship

In [43]:
invalid_ids = performance_clean[
    ~performance_clean["EmployeeID"].isin(employee_clean["EmployeeID"])
]

print("Performance records with invalid EmployeeID:", len(invalid_ids))

Performance records with invalid EmployeeID: 0

### Check number of reviews per employee

In [44]:
reviews_per_employee = (
    performance_clean
    .groupby("EmployeeID")
    .size()
    .reset_index(name="ReviewCount")
)

print(reviews_per_employee.head(10))

  EmployeeID  ReviewCount
0  005C-E0FB            3
1  00A3-2445            8
2  00B0-F199            9
3  00D4-DD53           10
4  00E4-3D60            9
5  0145-DBFC            6
6  0172-B5D2            1
7  017D-0B97            1
8  0210-E0D8            9
9  022A-0219            8

In [45]:
print("Minimum reviews:", reviews_per_employee["ReviewCount"].min())
print("Maximum reviews:", reviews_per_employee["ReviewCount"].max())
print("Average reviews:", reviews_per_employee["ReviewCount"].mean())

Minimum reviews: 1
Maximum reviews: 10
Average reviews: 5.24140625

### Check the review dates

In [47]:
print("Earliest Review Date:",
      performance_clean["ReviewDate"].min())

print("Latest Review Date:",
      performance_clean["ReviewDate"].max())

Earliest Review Date: 2013-01-02 00:00:00
Latest Review Date: 2022-12-31 00:00:00

### Create Review Year

In [49]:
performance_clean["ReviewYear"] = (
    performance_clean["ReviewDate"].dt.year
)

In [50]:
print(performance_clean["ReviewYear"].value_counts().sort_index())

ReviewYear
2013     151
2014     285
2015     411
2016     529
2017     630
2018     722
2019     836
2020     965
2021    1055
2022    1125
Name: count, dtype: int64

### Create an Overall Performance Score

In [51]:
performance_clean["OverallPerformanceScore"] = (
    performance_clean["SelfRating"] +
    performance_clean["ManagerRating"]
) / 2

In [52]:
performance_clean[
    [
        "EmployeeID",
        "ReviewDate",
        "SelfRating",
        "ManagerRating",
        "OverallPerformanceScore"
    ]
].head(10)

  EmployeeID ReviewDate  SelfRating  ManagerRating  OverallPerformanceScore
0  79F7-78EC 2013-01-02           4              4                      4.0
1  B61E-0F26 2013-01-03           4              3                      3.5
2  F5E3-48BB 2013-01-03           5              4                      4.5
3  0678-748A 2013-01-04           3              2                      2.5
4  541F-3E19 2013-01-04           4              3                      3.5
5  F93E-BDEF 2013-01-04           4              4                      4.0
6  9E7A-1F70 2013-01-08           4              3                      3.5
7  05ED-92F1 2013-01-10           3              2                      2.5
8  F72D-261D 2013-01-10           5              4                      4.5
9  774E-685D 2013-01-11           5              4                      4.5

### Validate the 3 Lookup Tables

In [53]:
print("EDUCATION LEVEL")
print(education_clean)

print("\nRATING LEVEL")
print(rating_clean)

print("\nSATISFACTION LEVEL")
print(satisfaction_clean)

EDUCATION LEVEL
   EducationLevelID            EducationLevel
0                 1  No Formal Qualifications
1                 2               High School
2                 3                 Bachelors
3                 4                   Masters
4                 5                 Doctorate

RATING LEVEL
   RatingID          RatingLevel
0         1         Unacceptable
1         2    Needs Improvement
2         3    Meets Expectation
3         4  Exceeds Expectation
4         5     Above and Beyond

SATISFACTION LEVEL
   SatisfactionID  SatisfactionLevel
0               1  Very Dissatisfied
1               2       Dissatisfied
2               3            Neutral
3               4          Satisfied
4               5     Very Satisfied

### Check IDs

In [54]:
print("Education IDs:", sorted(education_clean["EducationLevelID"].unique()))
print("Rating IDs:", sorted(rating_clean["RatingID"].unique()))
print("Satisfaction IDs:", sorted(satisfaction_clean["SatisfactionID"].unique()))

Education IDs: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Rating IDs: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Satisfaction IDs: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

### Export the files

In [55]:
import os

os.makedirs("cleaned_data", exist_ok=True)

In [56]:
employee_clean.to_csv(
    "cleaned_data/Employee_Clean.csv",
    index=False
)

performance_clean.to_csv(
    "cleaned_data/PerformanceRating_Clean.csv",
    index=False
)

education_clean.to_csv(
    "cleaned_data/EducationLevel_Clean.csv",
    index=False
)

rating_clean.to_csv(
    "cleaned_data/RatingLevel_Clean.csv",
    index=False
)

satisfaction_clean.to_csv(
    "cleaned_data/SatisfiedLevel_Clean.csv",
    index=False
)

print("All cleaned datasets exported successfully.")

All cleaned datasets exported successfully.

In [57]:
os.listdir("cleaned_data")

['EducationLevel_Clean.csv',
 'Employee_Clean.csv',
 'PerformanceRating_Clean.csv',
 'RatingLevel_Clean.csv',
 'SatisfiedLevel_Clean.csv']